# Generated by Django 3.2.11 on 2022-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTopNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='System notification content')),
                ('expired', models.BooleanField(default=False, help_text='Is the notification expired')),
                ('publish_time', models.DateTimeField(auto_now=True, help_text='Time of publishing the notification')),
                ('category', models.CharField(choices=[('hint', 'hint'), ('alert', 'alert')], help_text='Category of the notification', max_length=128)),
            ],
        ),
    ]
